-- =====================================================================
-- India UPI Generator & Wagal Macro - Backend Database Schema
-- Supabase 대시보드 -> SQL Editor에 붙여넣고 [RUN]을 누르면 생성됩니다.
-- =====================================================================

-- 1. 와갈매크로 성공 및 시도 횟수 기록 테이블
CREATE TABLE IF NOT EXISTS public.macro_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempts INT NOT NULL CHECK (attempts >= 1 AND attempts <= 500),
    duration_sec INT DEFAULT 0,
    version TEXT DEFAULT '0.4.0',
    product TEXT DEFAULT 'YouTube Premium',
    currency TEXT DEFAULT 'INR',
    client_type TEXT DEFAULT 'extension' CHECK (client_type IN ('extension', 'bookmarklet', 'web_sim')),
    created_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. 검색 및 실시간 통계 속도를 위한 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_macro_logs_created_at ON public.macro_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_macro_logs_attempts ON public.macro_logs(attempts);
CREATE INDEX IF NOT EXISTS idx_macro_logs_version ON public.macro_logs(version);

-- 3. Row Level Security (RLS) 활성화
ALTER TABLE public.macro_logs ENABLE ROW LEVEL SECURITY;

-- 4. RLS 정책: 누구나 통계 조회(SELECT) 가능
CREATE POLICY "Allow public read macro_logs" 
ON public.macro_logs 
FOR SELECT 
TO anon, authenticated 
USING (true);

-- 5. RLS 정책: 누구나 성공 결과 전송(INSERT) 가능
CREATE POLICY "Allow public insert macro_logs" 
ON public.macro_logs 
FOR INSERT 
TO anon, authenticated 
WITH CHECK (true);

-- 6. 원격 동적 설정 테이블 (쿠팡, 고잉버스, 긴급 공지, 최신 버전 관리)
CREATE TABLE IF NOT EXISTS public.app_configs (
    key TEXT PRIMARY KEY,
    value JSONB NOT NULL,
    description TEXT DEFAULT '',
    updated_at TIMESTAMPTZ DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.app_configs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read app_configs" 
ON public.app_configs 
FOR SELECT 
TO anon, authenticated 
USING (true);

-- 7. 초기 기본 설정값 등록 (이미 존재하면 건너뜀)
INSERT INTO public.app_configs (key, value, description)
VALUES 
    ('coupang', '{"url": "https://link.coupang.com/a/g03lOjRufc", "subId": "indouidid", "active": true}'::jsonb, '쿠팡 파트너스 최신 제휴 링크'),
    ('goingbus', '{"url": "https://goingbus.com?s=1kO9X8Oz", "code": "1kO9X8Oz", "active": true}'::jsonb, '고잉버스 추천 링크'),
    ('macro_meta', '{"latestVersion": "0.4.0", "minSupportedVersion": "0.3.0", "killSwitch": false, "recommendedAttempts": 15, "recommendedIntervalSec": 25}'::jsonb, '와갈매크로 버전 및 실행 권장 설정'),
    ('emergency_notice', '{"active": false, "title": "애플 결제망 상태 정상", "message": "현재 정상적으로 갱신 시도가 가능합니다."}'::jsonb, '긴급 킬스위치 및 공지')
ON CONFLICT (key) DO NOTHING;

-- 8. 초기 샘플 통계 데이터 등록 (신규 테이블일 때 초기 통계 베이스)
INSERT INTO public.macro_logs (attempts, duration_sec, version, product, client_type, created_at)
VALUES
    (7, 130, '0.4.0', 'YouTube Premium', 'extension', NOW() - INTERVAL '5 minutes'),
    (11, 215, '0.4.0', 'YouTube Premium', 'extension', NOW() - INTERVAL '14 minutes'),
    (4, 82, '0.4.0', 'YouTube Premium', 'bookmarklet', NOW() - INTERVAL '28 minutes'),
    (15, 290, '0.4.0', 'YouTube Premium', 'extension', NOW() - INTERVAL '45 minutes'),
    (8, 155, '0.4.0', 'YouTube Premium', 'extension', NOW() - INTERVAL '1 hour'),
    (19, 360, '0.4.0', 'YouTube Premium Family', 'extension', NOW() - INTERVAL '2 hours'),
    (6, 115, '0.4.0', 'YouTube Premium', 'extension', NOW() - INTERVAL '3 hours'),
    (12, 230, '0.4.0', 'YouTube Premium', 'extension', NOW() - INTERVAL '4 hours')
ON CONFLICT DO NOTHING;
